### PR TITLE
New txt file created

### PR DESCRIPTION
**Pull request by kocevaIv**
Creating a pull request

### CODE REVIEW

**Comment by kocevaIv** [comment]
Merge changes

**Comment by kocevaIv** [comment]
Hey, can i reopen the pull request and do it correctly?

**Comment by ivinskyi** [comment]
Yes, can you merge it now?

**Comment by kocevaIv** [comment]
Is it okay now?

**Comment by ivinskyi** [comment]
The message looks unusual 
```
kocevaIv referenced this pull request from commit 9d7955d about 2 hours ago
kocevaIv merged commit 9d7955d into master about 2 hours ago
```
I was expecting the message to be `kocevaIv merged pull request #1 into master about 2 hours ago`.

But the status `Merged` is correct. I guess it is alright.

**Pull request merged**
